const options = {
  fruitRougeOptions: [
    { value: "Pomme", label: "Pomme" },
    { value: "Pêche", label: "Pêche" },
    { value: "Poire", label: "Poire" },
    { value: "Banane", label: "Banane" },
    { value: "Groseille", label: "Groseille" },
    { value: "Cassis", label: "Cassis" },
    { value: "Framboise", label: "Framboise" },
    { value: "Fraise", label: "Fraise" },
    { value: "Mûre", label: "Mûre" },
    { value: "Cerise", label: "Cerise" },
    { value: "Pelure orange", label: "Pelure orange" },
    { value: "Gelée prune", label: "Gelée prune" },
    { value: "Pamplemousse", label: "Pamplemousse" },
    { value: "Pruneau", label: "Pruneau" },
  ],
  fruitBlancOptions: [
    { value: "Pomme", label: "Pomme" },
    { value: "Pêche", label: "Pêche" },
    { value: "Poire", label: "Poire" },
    { value: "Banane", label: "Banane" },
    { value: "Citron", label: "Citron" },
    { value: "Cassis", label: "Cassis" },
    { value: "Ananas", label: "Ananas" },
    { value: "Melon", label: "Melon" },
    { value: "Abricot sec", label: "Abricot sec" },
    { value: "Raisin sec", label: "Raisin sec" },
    { value: "Abricot", label: "Abricot" },
    { value: "Coing", label: "Coing" },
    { value: "Pamplemousse", label: "Pamplemousse" },
    { value: "Mangue", label: "Mangue" },
    { value: "Fruit de la passion", label: "Fruit de la passion" },
    { value: "Compote de pomme", label: "Compote de pomme" },
    { value: "Compote de poire", label: "Compote de poire" },
    { value: "Marmelade d'orange", label: "Marmelade d'orange" },
  ],
  fleurRougeOptions: [
    { value: "Aubépine", label: "Aubépine" },
    { value: "Acacia", label: "Acacia" },
    { value: "Chèvrefeuille", label: "Chèvrefeuille" },
    { value: "Jasmin", label: "Jasmin" },
    { value: "Rose", label: "Rose" },
    { value: "Tilleul", label: "Tilleul" },
    { value: "Lilas", label: "Lilas" },
    { value: "Violette", label: "Violette" },
  ],
  fleurBlancOptions: [
    { value: "Achillé", label: "Achillé" },
    { value: "Fleur d'acacia", label: "Fleur d'acacia" },
    { value: "Géranium", label: "Géranium" },
    { value: "Jasmin", label: "Jasmin" },
    { value: "Rose", label: "Rose" },
    { value: "Lilas", label: "Lilas" },
  ],
  vegetalRougeOptions: [
    { value: "Herbe", label: "Herbe" },
    { value: "Eucalyptus", label: "Eucalyptus" },
    { value: "Foin coupé", label: "Foin coupé" },
    { value: "Sous bois", label: "Sous bois" },
    { value: "Fougère", label: "Fougère" },
    { value: "Thym", label: "Thym" },
    { value: "Fougère", label: "Fougère" },
    { value: "Poivron", label: "Poivron" },
    { value: "Baie de genièvre", label: "Baie de genièvre" },
    { value: "Coquille de noix vert", label: "Coquille de noix vert" },
    { value: "Fève verte", label: "Fève verte" },
    { value: "Buis", label: "Buis" },
    { value: "Humus", label: "Humus" },
    { value: "Betterave", label: "Betterave" },
    { value: "Olive noire", label: "Olive noire" },
    { value: "Thé noire", label: "Thé noire" },
    { value: "Pin", label: "Pin" },
    { value: "Résine", label: "Résine" },
    { value: "Camphre", label: "Camphre" },
    { value: "Humus", label: "Humus" },
    { value: "Bois sec", label: "Bois sec" },
    { value: "Cèdre", label: "Cèdre" },
  ],
  vegetalBlancOptions: [
    { value: "Herbe fraîche", label: "Herbe fraîche" },
    { value: "Eucalyptus", label: "Eucalyptus" },
    { value: "Menthe", label: "Menthe" },
    { value: "Haricot vert", label: "Haricot vert" },
    { value: "Acide phénique", label: "Acide phénique" },
    { value: "Asperge verte", label: "Asperge verte" },
    { value: "Artichaut", label: "Artichaut" },
    { value: "Foin", label: "Foin" },
    { value: "Thé", label: "Thé" },
  ],
  epiceRougeOptions: [
    { value: "Poivre", label: "Poivre" },
    { value: "Menthe", label: "Menthe" },
    { value: "Canelle", label: "Canelle" },
    { value: "Réglisse", label: "Réglisse" },
    { value: "Livèche", label: "Livèche" },
    { value: "Vanille", label: "Vanille" },
    { value: "Clou de girofle", label: "Clou de girofle" },
    { value: "Amande", label: "Amande" },
    { value: "Noisette", label: "Noisette" },
  ],
  epiceBlancOptions: [
    { value: "Livèche", label: "Livèche" },
    { value: "Vanille", label: "Vanille" },
    { value: "Clou de girofle", label: "Clou de girofle" },
    { value: "Canelle", label: "Canelle" },
    { value: "Noisette", label: "Noisette" },
    { value: "Noix de muscade", label: "Noix de muscade" },
    { value: "Gingembre", label: "Gingembre" },
    { value: "Poivre noir", label: "Poivre noir" },
    { value: "Amande grillée", label: "Amande grillée" },
    { value: "Noix", label: "Noix" },
  ],
  ampyreumatiqueRougeOptions: [
    { value: "Fumé", label: "Fumé" },
    { value: "Toasté", label: "Toasté" },
    { value: "Pain grillé", label: "Pain grillé" },
    { value: "Café", label: "Café" },
    { value: "Caramel", label: "Caramel" },
    { value: "Mocha", label: "Mocha" },
    { value: "Cacao", label: "Cacao" },
    { value: "Malt", label: "Malt" },
    { value: "Mélasse", label: "Mélasse" },
    { value: "Goudron", label: "Goudron" },
    { value: "Bacon fumé", label: "Bacon fumé" },
    { value: "Cuir", label: "Cuir" },
    { value: "Fourrure", label: "Fourrure" },
    { value: "Gibier", label: "Gibier" },
  ],
  ampyreumatiqueBlancOptions: [
    { value: "Caramel", label: "Caramel" },
    { value: "Malt", label: "Malt" },
    { value: "Miel", label: "Miel" },
    { value: "Cire d'abeille", label: "Cire d'abeille" },
    { value: "Cuir", label: "Cuir" },
    { value: "Bacon fumé", label: "Bacon fumé" },
    { value: "Goudron", label: "Goudron" },
    { value: "Résine", label: "Résine" },
    { value: "Vieux meuble bois", label: "Vieux meuble bois" },
    { value: "Schiste mouillé", label: "Schiste mouillé" },
    { value: "Terre", label: "Terre" },
  ],
  mineralRougeOptions: [
    { value: "Iode", label: "Iode" },
    { value: "Pétrole", label: "Pétrole" },
    { value: "Carton", label: "Carton" },
    { value: "Colle", label: "Colle" },
    { value: "Pierre à fusil", label: "Pierre à fusil" },
    { value: "Silex", label: "Silex" },
  ],
  mineralBlancOptions: [
    { value: "Yaourt", label: "Yaourt" },
    { value: "Beurre", label: "Beurre" },
    { value: "Laine mouillée", label: "Laine mouillée" },
    { value: "Champignon", label: "Champignon" },
    { value: "Sous bois", label: "Sous bois" },
    { value: "Oxydé", label: "Oxydé" },
    { value: "Sueur", label: "Sueur" },
  ],
};

export default options;
