export const BOUCHE = {
  fleursRouges: {
    fleur1: "Aubépine",
    fleur2: "Acacia",
    fleur3: "Chèvrefeuille",
    fleur4: "Jasmin",
    fleur5: "Rose",
    fleur6: "Tilleul",
    fleur7: "Lilas",
    fleur8: "Violette",
  },
  fleursBlancs: {
    fleur1: "Achillé",
    fleur2: "Fleur d'acacia",
    fleur3: "Géranium",
    fleur4: "Jasmin",
    fleur5: "Rose",
    fleur6: "Lilas",
  },
  vegetalRouge: {
    vegetal1: "Herbe",
    vegetal2: "Eucalyptus",
    vegetal3: "Foin coupé",
    vegetal4: "Sous bois",
    vegetal5: "Fougère",
    vegetal6: "Thym",
    vegetal7: "Poivron",
    vegetal8: "Baie de genièvre",
    vegetal9: "Coquille de noix vert",
    vegetal10: "Fève verte",
    vegetal11: "Buis",
    vegetal12: "Humus",
    vegetal13: "Betterave",
    vegetal14: "Olive noire",
    vegetal15: "Thé noire",
    vegetal16: "Pin",
    vegetal17: "Résine",
    vegetal18: "Camphre",
    vegetal19: "Bois sec",
    vegetal20: "Cèdre",
  },
  vegetalBlanc: {
    vegetal1: "Herbe fraîche",
    vegetal2: "Eucalyptus",
    vegetal3: "Menthe",
    vegetal4: "Haricot vert",
    vegetal5: "Acide phénique",
    vegetal6: "Asperge verte",
    vegetal7: "Artichaut",
    vegetal8: "Foin",
    vegetal9: "Thé",
  },
  epiceRouge: {
    epice1: "Poivre",
    epice2: "Menthe",
    epice3: "Canelle",
    epice4: "Réglisse",
    epice5: "Livèche",
    epice6: "Vanille",
    epice7: "Clou de girofle",
    epice8: "Amande",
    epice9: "Noisette",
  },
  epiceBlanc: {
    epice1: "Livèche",
    epice2: "Vanille",
    epice3: "Clou de girofle",
    epice4: "Canelle",
    epice5: "Noisette",
    epice6: "Noix de muscade",
    epice7: "Gingembre",
    epice8: "Poivre noir",
    epice9: "Amande grillée",
    epice10: "Noix",
  },
  ampyreumatiqueRouge: {
    ampyreumatique1: "Fumé",
    ampyreumatique2: "Toasté",
    ampyreumatique3: "Pain grillé",
    ampyreumatique4: "Café",
    ampyreumatique5: "Caramel",
    ampyreumatique6: "Mocha",
    ampyreumatique7: "Cacao",
    ampyreumatique8: "Malt",
    ampyreumatique9: "Mélasse",
    ampyreumatique10: "Goudron",
    ampyreumatique11: "Bacon fumé",
    ampyreumatique12: "Cuir",
    ampyreumatique13: "Fourrure",
    ampyreumatique14: "Gibier",
  },
  ampyreumatiqueBlanc: {
    ampyreumatique1: "Caramel",
    ampyreumatique2: "Malt",
    ampyreumatique3: "Miel",
    ampyreumatique4: "Cire d'abeille",
    ampyreumatique5: "Cuir",
    ampyreumatique6: "Bacon fumé",
    ampyreumatique7: "Goudron",
    ampyreumatique8: "Résine",
    ampyreumatique9: "Vieux meuble bois",
    ampyreumatique10: "Schiste mouillé",
    ampyreumatique11: "Terre",
  },
  mineralRouge: {
    mineral1: "Iode",
    mineral2: "Pétrole",
    mineral3: "Carton",
    mineral4: "Colle",
    mineral5: "Pierre à fusil",
    mineral6: "Silex",
  },
  mineralBlanc: {
    mineral1: "Yaourt",
    mineral2: "Beurre",
    mineral3: "Laine mouillée",
    mineral4: "Champignon",
    mineral5: "Sous bois",
    mineral6: "Oxydé",
    mineral7: "Sueur",
  },
};

const options = {
  fruitRougeOptions: [
    { value: "Pomme", label: "Pomme" },
    { value: "Pêche", label: "Pêche" },
    { value: "Poire", label: "Poire" },
    { value: "Banane", label: "Banane" },
    { value: "Groseille", label: "Groseille" },
    { value: "Cassis", label: "Yellow" },
    { value: "Framboise", label: "Framboise" },
    { value: "Fraise", label: "Fraise" },
    { value: "Mûre", label: "Mûre" },
    { value: "Cerise", label: "Cerise" },
    { value: "Pelure orange", label: "Pelure orange" },
    { value: "Gelée prune", label: "Gelée prune" },
    { value: "Pamplemousse", label: "Pamplemousse" },
    { value: "Pruneau", label: "Pruneau" },
  ],
  fruitBlancOptions: [
    { value: "Pomme", label: "Pomme" },
    { value: "Pêche", label: "Pêche" },
    { value: "Poire", label: "Poire" },
    { value: "Banane", label: "Banane" },
    { value: "Citron", label: "Citron" },
    { value: "Cassis", label: "Yellow" },
    { value: "Ananas", label: "Ananas" },
    { value: "Melon", label: "Melon" },
    { value: "Abricot sec", label: "Abricot sec" },
    { value: "Raisin sec", label: "Raisin sec" },
    { value: "Abricot", label: "Abricot" },
    { value: "Coing", label: "Coing" },
    { value: "Pamplemousse", label: "Pamplemousse" },
    { value: "Mangue", label: "Mangue" },
    { value: "Fruit de la passion", label: "Fruit de la passion" },
    { value: "Compote de pomme", label: "Compote de pomme" },
    { value: "Compote de poire", label: "Compote de poire" },
    { value: "Marmelade d'orange", label: "Marmelade d'orange" },
  ],
};

export default options;
